### ISSUE TITLE
Circuit and constructor model sort/filter requires a search query to work

### ISSUE THREAD

**Issue by Kvnmedina** [UT-SWLab/TeamE2#95]
Currently it appears you can't sort/filter if you don't enter something into the query search bar. This means you can't sort/filter all instances of a circuit or constructor, only a subset.

Unlike the drivers model page, this one doesn't seem fixable by just removing the "required" part of the \<input\>\</input\> tag.

**Comment by edie-zhou** [comment]
I have modified the search/filter/sort form to accept blank entries
