### ISSUE TITLE
Constructor top driver (A-Z) and (Z-A) search crashes

### ISSUE THREAD

**Issue by Kvnmedina** [UT-SWLab/TeamE2#96]
If you search constructors by top driver and then sort by either (A-Z) or (Z-A), the website crashes (TypeError: 'NoneType' object is not iterable).

To replicate: Search constructors = Top Driver, Sorted by = Alphabetical (A-Z), Search query = bottas

Sorting by relevance appears to work fine.

**Comment by edie-zhou** [comment]
this bug was caused by leftover database entries with minimal data causing KeyError exceptions, no change has been made to the code
